language: ruby
cache: bundler
services:
  - mysql
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
    condition: "-d build"
before_install:
  - bundle update --bundler
install:
  - git fetch origin gh-pages:gh-pages
  - bundle install --deployment
# From https://www.tekz.io/blog/travis-ci-running-tests-on-mysql-8-0-x-on-ubuntu-xenial
sudo: true
before_script:
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version
script: bin/travis.sh
